# Generated by Django 5.2.8 on 2025-11-28 14:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='name',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message='O nome de usuário pode conter letras, números e espaços, mas não pode começar ou terminar com espaço.', regex='^[A-Za-z0-9À-ÿ]+(?: [A-Za-z0-9À-ÿ]+)*$')]),
        ),
    ]
